[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "highrise-bot-sdk>=24.1.0",
    "openai>=0.28.1",
    "sqlitedict>=2.1.0",
]
